name: Action
on:
  push:
    branches: [ main ]

jobs:
  build:
    environment: ${{ github.workspace }}/actions/build
    name: KRapp-server
    runs-on: windows-latest
    env:
      VCPKG_DEFAULT_TRIPLET: x64-windows
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      # Get CMake
      - name: get-cmake
        uses: lukka/get-cmake@v3.19.0
      # Setup vcpkg
      - name: Run vcpkg
        uses: lukka/run-vcpkg@v10
        with:
          vcpkgDirectory: '${{ github.workspace }}/actions/vcpkg'
          vcpkgGitCommitId: '52955a7ae52bbf821a603e4e3be49ab7e437639b'
          runVcpkgInstall: true
          appendedCacheKey: ${{ hashFiles( '**/vcpkg.json' ) }}
          vcpkgTriplet: 'x64-windows' # Later change to static
          additionalCachedPaths: '${{ env.buildDir }}/actions/vcpkg_installed'
      - name: Run CMake with Ninja, install dependencies with vcpkg, build with CMake
        uses: lukka/run-cmake@v10
        with:
          cmakeListsOrSettingsJson: CMakeListsTxtBasic
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          useVcpkgToolchainFile: true
          buildDirectory: '${{ env.buildDir }}'
